name: movie_browser
description: Movie Browser with OMDb API
publish_to: "none"
version: 0.1.20+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  intl: ^0.20.2
  flutter_hooks: ^0.20.3
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.1
  talker: ^5.0.0
  talker_flutter: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_move_browser.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon_move_browser.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - .env
